/* CharacterOS — static showcase build. No server, no live bridge. */
(()=>{'use strict';
const B=JSON.parse(document.getElementById('boot-data').textContent),C=window.CharacterOS||window.SUA;
const $=(s,el=document)=>el.querySelector(s),$$=(s,el=document)=>Array.from(el.querySelectorAll(s));
const root=$('#root'),modalRoot=$('#modal-root'),STORE='characteros-workspace-1.0';
const glyphs={plus:'M12 5v14M5 12h14',arrow:'M5 12h14m-5-5 5 5-5 5',close:'m6 6 12 12M6 18 18 6',download:'M12 3v12m-5-5 5 5 5-5M5 16v5h14v-5',upload:'M12 16V3m-5 5 5-5 5 5M5 16v5h14v-5',graph:'M6 6l12 2-6 10L6 6m0 0v0M5 5h2v2H5zm12 2h2v2h-2zm-6 10h2v2h-2z',book:'M12 5C8 3 5 3 3 4v15c4-1 6 0 9 2m0-16c4-2 7-2 9-1v15c-4-1-6 0-9 2V5',spark:'m12 3 2.4 6.6L21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4L12 3',copy:'M9 9h11v11H9zM15 9V4H4v11h5',edit:'m4 16 12-12 4 4L8 20H4v-4m10-10 4 4',undo:'M9 4 3 10l6 6M3 10h10c7 0 7 10 0 10',check:'m5 12 4 4L19 6',fit:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5',minus:'M5 12h14',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 3v3m0 12v3M3 12h3m12 0h3M5.6 5.6l2.1 2.1m8.6 8.6 2.1 2.1M5.6 18.4l2.1-2.1m8.6-8.6 2.1-2.1',asset:'M3 4h18v16H3zM3 16l6-7 5 6 3-3 4 5M16 8h.1',analyst:'M3 3v18h18M7 16l4-6 4 4 5-8',constellation:'M12 2l3 7h7l-5.5 4 2 7-6.5-4.5L6.5 20l2-7L3 9h7z',chronology:'M12 8v4l3 3m6-3a9 9 0 1 1-18 0 9 9 0 0 1 18 0z'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${glyphs[name]||glyphs.spark}"/></svg>`;
const e=C.esc;
const LOGO_SRC = /*__LOGO_SRC__*/ 'logo.png';
const btn=(label,action,cls='',attrs='')=>`<button class="btn ${cls}" data-action="${action}" ${attrs}>${label}</button>`;
function brand(){return `<div class="brand"><img class="brand-logo" src="${LOGO_SRC}" alt="CharacterOS" height="62"></div>`;}

// Blank-first: only restore saved work if this browser has been seen before.
let seen=false;try{seen=!!(localStorage.getItem('characteros-seen')||localStorage.getItem('sua-seen'));}catch{}
const readSaved=()=>{if(!seen||B.portable)return null;try{const s=JSON.parse(localStorage.getItem(STORE)||localStorage.getItem('sua-workspace-1.0'));return(s&&C.validate(s.u,B.schema,B.archetypes).ok)?s:null;}catch{return null;}};
const saved=readSaved();
const initial=B.initial||null;
const haveInitial=initial&&C.validate(initial,B.schema,B.archetypes).ok;
const useSaved=saved&&(!haveInitial||saved.u?.title===initial.title);

let S={u:haveInitial?C.clone(initial):(useSaved?.u?C.clone(useSaved.u):null),phase:haveInitial?(initial.relationships?.length?'studio':'cast'):'studio',tab:'graph',selected:null,positions:{},box:{x:0,y:0,w:900,h:600},filter:'all',search:'',undo:[],analysisStale:false,awaiting:false,request:null,castCollapsed:false,minimapVisible:true,...B.initial_view,...(useSaved||{})};
if(haveInitial){S.u=C.clone(initial);if(!useSaved){S.positions={};S.box={x:0,y:0,w:900,h:600};}}
S.undo=[];
if(!['graph','seeds','assets','suggestions','chronology','analyst'].includes(S.tab))S.tab='graph';

const colors=[['#9a3412','#fbf1e6'],['#0f766e','#e6f5f3'],['#991b1b','#faecec'],['#1e40af','#eef3fb'],['#166534','#edf7ee'],['#854d0e','#fcf6e5'],['#701a75','#f8edf7']];
const color=c=>colors[Math.max(0,S.u.characters.findIndex(x=>x.id===c.id))%colors.length];
const initials=name=>name.split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join('');
function store(){if(B.portable)return;try{if(S.u){localStorage.setItem('characteros-seen','1');localStorage.setItem('sua-seen','1');}localStorage.setItem(STORE,JSON.stringify({u:S.u,phase:S.phase,tab:S.tab,selected:S.selected,positions:S.positions,box:S.box,analysisStale:S.analysisStale,castCollapsed:S.castCollapsed,minimapVisible:S.minimapVisible}));}catch{}}
function transitionUI(fn){if(document.startViewTransition&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){document.startViewTransition(fn);}else{fn();}}
function toast(text,canUndo=false){const t=$('#toast');if(!t)return;t.innerHTML=`<span>${e(text)}</span>${canUndo&&S.undo.length?`<button class="toast-undo" data-action="undo">Undo</button>`:''}`;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),5000);}
let toastTimer=null;
function change(next,label,editorial=false){const check=C.validate(next,B.schema,B.archetypes);if(!check.ok)throw Error(check.errors.join('\n'));S.undo.push({u:C.clone(S.u),phase:S.phase,analysisStale:S.analysisStale});if(S.undo.length>30)S.undo.shift();S.u=next;if(editorial)S.analysisStale=true;store();render();if(label)toast(label,true);}
function monogram(c,cls=''){const[col,wash]=color(c);return `<span class="monogram ${cls}" style="--color:${col};--wash:${wash}">${e(initials(c.name))}</span>`;}
function badge(){const modes={'curated-example':'Curated example · no live call','imported':'Imported story record','draft':'Story draft'};return `<span class="badge ${S.u.provenance.mode==='draft'?'live':''}"><span class="dot"></span>${modes[S.u.provenance.mode]||'Imported story'}</span>`;}
// ---- blank + placeholder states ----------------------------------------------
function blankEmptyHTML(){return `<header class="topbar">${brand()}${btn(icon('plus')+' New story','new','small')}${btn(icon('upload')+' Add a universe','connect','small')}${btn(icon('download')+' Export','export','primary small','disabled')}</header>
<main class="workspace blank">
 <div class="empty-stage">
   <div class="empty-orbit" aria-hidden="true"><span></span><span></span><span></span></div>
   <h1 class="empty-title">Awaiting a story</h1>
   <p class="empty-sub">Drag a universe <code>.json</code> onto this page, open <strong>Add a universe</strong>, or start from a <strong>New story</strong> premise. This is a static showcase — nothing is sent anywhere.</p>
   <div class="empty-actions">${btn(icon('plus')+' New story','new','primary')}${btn(icon('upload')+' Add a universe','connect','')}</div>
   <div class="dropzone" data-action="import-universe" role="button" tabindex="0" aria-label="Open a universe file">Drop a <code>.json</code> file here, or click to browse</div>
 </div>
</main>`;}
function blankSkeletonHTML(){return `<header class="topbar">${brand()}${btn('Cancel request','cancel-pending','small')}</header>
<main class="workspace blank">
 <div class="skeleton-stage" aria-hidden="true">
   <div class="sk sk-title"></div><div class="sk sk-line"></div>
   <div class="sk-grid">${'<div class="sk-card"></div>'.repeat(4)}</div>
   <div class="sk sk-graph"></div>
 </div>
 <p class="empty-sub skeleton-note"><span class="spinner"></span> Generating your universe…</p>
</main>`;}

function render(){
 document.documentElement.style.setProperty('--cast-w',S.castCollapsed?'56px':'268px');
 if(!S.u){root.innerHTML=S.awaiting?blankSkeletonHTML():blankEmptyHTML();document.title='CharacterOS';return;}
 const u=S.u;const phaseIndex={cast:1,relationships:2,studio:3}[S.phase]??3;document.title=u.title+' — CharacterOS';
 root.innerHTML=`
<header class="topbar">${brand()}${btn(icon('plus')+'New story','new','small')}${btn(icon('upload')+'Add a universe','connect','small')}${btn(icon('download')+'Export','export','primary small')}</header>
<main class="workspace"><section class="story-head"><div class="story-title-row"><div><div class="eyebrow">${e(u.format)} <span class="sep">/</span> ${e(u.genre)}</div><h1 class="story-title">${e(u.title)}</h1></div><div class="story-controls">${btn(icon('edit')+'Story brief','edit-story','small')}${btn(icon('undo'),'undo','small',`aria-label="Undo last edit" ${S.undo.length?'':'disabled'}`)}</div></div><p class="logline">${e(u.concept)}</p></section>
<div class="stepper">${['Premise','Review cast','Map relationships','Creative kit'].map((t,i)=>`<div class="step ${i<phaseIndex?'done':i===phaseIndex?'current':''}"><span>${i<phaseIndex?'✓':i+1}</span>${t}</div>${i<3?'<div class="step-line"></div>':''}`).join('')}<div class="step-right"><span class="micro">Revision ${u.revision}</span>${btn('Guided review','guided','ghost small')}</div></div>
${S.awaiting?`<div class="wide-banner"><div><strong>Generation in progress.</strong><small>The current view stays empty until you load a result.</small></div>${btn('Show task','pending','small')}</div>`:''}
${S.analysisStale?`<div class="wide-banner warn"><div><strong>Editorial review needed after your edit.</strong><small>Outputs reflect current text. Check existing relationships and suggestions for narrative consistency.</small></div>${btn('Mark reviewed','reviewed','small')}</div>`:''}
${stageBanner()}
<nav class="tabs" aria-label="Universe views">${[['graph','graph','Relationship map',u.relationships.length],['chronology','chronology','Chronology',C.storyChronology(u).reduce((acc,p)=>acc+p.events.length,0)],['seeds','book','Story seeds',C.seeds(u).length],['assets','asset','Visual prompt kit',C.assets(u).length],['suggestions','spark','Cast suggestions',u.suggestions.filter(x=>x.status==='pending').length],['analyst','analyst','Story analyst',3]].map(([id,ic,title,n])=>`<button class="tab ${S.tab===id?'active':''}" data-action="tab" data-value="${id}" aria-current="${S.tab===id?'page':'false'}" ${S.phase==='cast'&&id!=='graph'?'disabled':''} ${S.phase==='relationships'&&['assets','seeds'].includes(id)?'disabled':''}>${icon(ic)}${title}<span class="count">${n}</span></button>`).join('')}</nav>
${S.phase==='cast'&&S.tab==='graph'?renderCastReview():S.tab==='graph'?renderGraphLayout():S.tab==='chronology'?renderChronology():S.tab==='assets'?renderAssets():S.tab==='seeds'?renderSeeds():S.tab==='suggestions'?renderSuggestions():S.tab==='analyst'?renderAnalyst():renderGraphLayout()}
<footer class="footbar"><span>${B.portable?'Portable copy · export to keep edits':(seen?'Saved in this browser · export for a portable copy':'Static showcase · export to preserve changes')} <span class="sep">·</span> One approved story record</span><button data-action="about" class="provenance-link">Sources, modes & limitations</button></footer></main>`;
 if(S.tab==='graph'&&S.phase!=='cast'){drawGraph();bindGraph();}}

function stageBanner(){if(S.phase==='cast')return `<div class="stage-banner"><div><h2>First, meet the people in your story.</h2><p>Review names, voices and desires. New mapping waits for your approval. Existing example connections remain available after review.</p></div>${btn('Approve cast & map relationships <span class="icon-capsule">'+icon('arrow')+'</span>','approve-cast','primary')}</div>`;if(S.phase==='relationships')return `<div class="stage-banner"><div><h2>What could make these relationships change?</h2><p>Inspect an edge. Review optional additions before compiling your creative kit.</p></div>${btn('Build creative kit <span class="icon-capsule">'+icon('arrow')+'</span>','approve-map','primary')}</div>`;return '';}
function renderCastReview(){return `<div class="content-grid cast-review">${S.u.characters.map((c,i)=>`<article class="card stagger-item" style="--stagger-i: ${i};">${monogram(c,'review-avatar')}<h3>${e(c.name)}</h3><div class="detail-sub">${e(c.role)} · ${e(c.archetype_label)}</div><div class="detail-block"><span class="detail-label">Wants / fears</span><p>${e(c.core_desire)}<br><em>${e(c.core_fear)}</em></p></div><div class="quote">“${e(c.voice_samples[0])}”</div><p>${e(c.backstory)}</p><div class="card-actions">${btn('Read full profile','profile','small',`data-id="${c.id}"`)}${btn(icon('edit')+'Edit','edit-character','small',`data-id="${c.id}"`)}</div></article>`).join('')}</div>`;}
function renderGraphLayout(){const isC=S.castCollapsed;return `<div class="graph-layout"><aside class="panel cast-panel ${isC?'collapsed':''}" aria-label="The approved cast" aria-expanded="${isC?'false':'true'}"><div class="panel-head"><div><div class="panel-title">The approved cast</div><div class="panel-caption">${S.u.characters.length} people, one story</div></div><div class="panel-head-actions"><span class="count">${S.u.characters.length}</span><button class="panel-toggle" data-action="toggle-cast" title="${isC?'Expand cast panel':'Collapse cast panel'}" aria-label="${isC?'Expand cast panel':'Collapse cast panel'}">${icon('arrow')}</button></div></div><div class="cast-list">${S.u.characters.map((c,i)=>`<button class="character-tile stagger-item ${S.selected?.type==='character'&&S.selected.id===c.id?'active':''}" style="--stagger-i: ${i};" data-action="select-character" data-id="${c.id}" title="${e(c.name)}">${monogram(c)}<span><span class="tile-name">${e(c.name)}</span><span class="tile-role">${e(c.role.split('·')[0])}</span></span><span class="tile-arrow">›</span></button>`).join('')}</div><div class="sidebar-note">A character is more than a lens.<br>Click a name to hear their voice.<br>Click a connection to find a scene.</div></aside><section class="panel graph-panel"><div class="graph-toolbar"><div><strong>Relationship atlas</strong><div class="panel-caption">Two perspectives on every connection</div></div><div class="toolbar-right">${graphButton('minus','zoom-out','Zoom out')}${graphButton('plus','zoom-in','Zoom in')}${graphButton('fit','fit','Fit graph')}${graphButton('graph','layout','Reset node layout')}</div></div><svg id="graph-canvas" role="group" aria-label="Interactive character relationship graph" viewBox="0 0 900 600"></svg>${renderMinimapHUD()}<div class="graph-foot"><span><span class="legend-line"></span>Selected connection</span><span>Drag to arrange · scroll to zoom</span><span class="keyboard-hint">Tab + Enter to inspect</span></div></section><aside class="panel inspector" aria-label="Selection details">${renderInspector()}</aside></div>`;}
function graphButton(ic,action,title){return `<button class="iconbtn" data-action="${action}" title="${title}" aria-label="${title}">${icon(ic)}</button>`;}
function selected(){return S.selected?.type==='character'?S.u.characters.find(c=>c.id===S.selected.id):S.u.relationships.find(r=>r.id===S.selected?.id);}
function block(label,text){return `<div class="detail-block"><span class="detail-label">${e(label)}</span><p>${e(text)}</p></div>`;}
function profile(c){return `<div class="detail-kicker">${e(c.archetype_label)}</div><h2 class="detail-title">${e(c.name)}</h2><div class="detail-sub">${e(c.role)}</div>${block('The person',c.backstory)}${block('How they communicate',c.communication_style)}${block('Emotional baseline',c.emotional_baseline)}<div class="tension-box"><span class="detail-label">Desire</span><p>${e(c.core_desire)}</p><span class="detail-label" style="margin-top:10px">Fear</span><p>${e(c.core_fear)}</p></div>${block('Behavioral tendencies',c.tendencies.join(' '))}<div class="detail-block"><span class="detail-label">Hear their voice</span>${c.voice_samples.map(q=>`<blockquote class="quote">“${e(q)}”</blockquote>`).join('')}</div>${block('Visual identity',c.appearance)}<div class="source-ref">Communication lens: ${e(c.archetype_id)}<br>Adapted from THRESHOLD; not a diagnosis.</div>`;}
function edgeDetail(r){const a=C.names(S.u,r.source),b=C.names(S.u,r.target);return `<div class="detail-kicker">${e(r.label)} · pressure ${r.intensity}/5</div><h2 class="detail-title">${e(a.split(' ')[0])} <span class="swap">↔</span> ${e(b.split(' ')[0])}</h2><div class="detail-sub">${e(a)} & ${e(b)}</div><div class="tension-box"><span class="detail-label">The instability</span><p>${e(r.tension)}</p></div>${block('What happened',r.shared_history)}<div class="detail-block"><span class="detail-label">One event. Two interpretations.</span><div class="perspective"><strong>${e(a)}</strong><p>${e(r.source_read)}</p></div><div class="perspective"><strong>${e(b)}</strong><p>${e(r.target_read)}</p></div></div>${block(a+' wants',r.source_wants)}${block(b+' wants',r.target_wants)}${block('The breaking point',r.breaking_point)}${block('What could happen',r.story_potential)}<div class="source-ref">${e(r.id)} · Writer-set pressure, not an objective score.</div>`;}
function renderInspector(){const item=selected();if(!item)return `<div class="panel-head"><span class="panel-title">The space between people</span></div><div class="inspector-body"><h2 class="detail-title">Choose a connection.</h2><p class="muted">Each edge holds two wants, a shared history and a possible breaking point.</p></div>`;const isC=S.selected.type==='character';return `<div class="panel-head"><span class="panel-title">${isC?'Character notes':'Relationship notes'}</span>${icon(isC?'book':'graph')}</div><div class="inspector-body">${isC?profile(item):edgeDetail(item)}</div><div class="inspector-actions">${btn(icon('edit')+'Edit '+(isC?'character':'relationship'),isC?'edit-character':'edit-edge','small',`data-id="${item.id}"`)}${!isC?btn('Find story seed','edge-seed','ghost small',`data-id="${item.id}"`):''}</div>`;}
function defaultPositions(){const active=new Set(S.u.characters.map(c=>c.id));for(const id of Object.keys(S.positions)){const p=S.positions[id];if(!active.has(id)||!p||typeof p.x!=='number'||typeof p.y!=='number'||isNaN(p.x)||isNaN(p.y)||p.x<-200||p.x>1500||p.y<-200||p.y>1200)delete S.positions[id];}const n=S.u.characters.length,fresh=!Object.keys(S.positions).length;let addedNew=false;S.u.characters.forEach((c,i)=>{if(!S.positions[c.id]){addedNew=true;const angle=-Math.PI/2+i*2*Math.PI/n;let pos={x:450+290*Math.cos(angle),y:300+205*Math.sin(angle)};if(!fresh){const existing=Object.values(S.positions),candidates=[];for(const scale of [1,1.25,1.5])for(let j=0;j<48;j++){const a=j*Math.PI/24,candidate={x:450+290*scale*Math.cos(a),y:300+205*scale*Math.sin(a)};candidate.clearance=Math.min(...existing.map(p=>Math.max(Math.abs(p.x-candidate.x)/236,Math.abs(p.y-candidate.y)/98)));candidate.scale=scale;candidates.push(candidate);}const clear=candidates.filter(p=>p.clearance>1.05).sort((a,b)=>a.scale-b.scale||b.clearance-a.clearance),best=clear[0]||candidates.sort((a,b)=>b.clearance-a.clearance)[0];pos={x:best.x,y:best.y};}S.positions[c.id]=pos;}});if(fresh||addedNew){const chars=S.u.characters;for(let iter=0;iter<6;iter++){let moved=false;for(let i=0;i<chars.length;i++){for(let j=i+1;j<chars.length;j++){const pi=S.positions[chars[i].id],pj=S.positions[chars[j].id];if(!pi||!pj)continue;const dx=pj.x-pi.x,dy=pj.y-pi.y,ox=236-Math.abs(dx),oy=94-Math.abs(dy);if(ox>0&&oy>0){if(ox<oy*1.8){const px=(ox/2)*(dx>=0?1:-1);pi.x-=px;pj.x+=px;}else{const py=(oy/2)*(dy>=0?1:-1);pi.y-=py;pj.y+=py;}moved=true;}}}if(!moved)break;}}}
function renderMinimapHUD(){return `<div class="minimap-hud ${S.minimapVisible?'':'minimized'}" id="minimap-hud"><div class="minimap-head" data-action="toggle-minimap" title="Toggle minimap radar"><span>RADAR</span><span class="micro">${S.minimapVisible?'▼':'▲'}</span></div><div class="minimap-body"><svg class="minimap-svg" id="minimap-svg" viewBox="-200 -100 1300 850" preserveAspectRatio="xMidYMid meet"></svg></div></div>`;}
function drawMinimap(){const svg=$('#minimap-svg');if(!svg||!S.minimapVisible)return;const positions=Object.values(S.positions);if(!positions.length)return;let minX=Math.min(-100,...positions.map(p=>p.x-120),S.box.x),maxX=Math.max(1000,...positions.map(p=>p.x+120),S.box.x+S.box.w),minY=Math.min(-50,...positions.map(p=>p.y-50),S.box.y),maxY=Math.max(650,...positions.map(p=>p.y+50),S.box.y+S.box.h);const pad=70;minX-=pad;minY-=pad;const mapW=(maxX-minX)+pad*2,mapH=(maxY-minY)+pad*2;svg.setAttribute('viewBox',`${minX} ${minY} ${mapW} ${mapH}`);const edges=S.u.relationships.map(r=>{const a=S.positions[r.source],b=S.positions[r.target];if(!a||!b)return '';const sel=S.selected?.type==='edge'&&S.selected.id===r.id;return `<line data-map-edge="${r.id}" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${sel?'var(--accent)':'var(--edge)'}" stroke-width="${sel?'7':'3.5'}" stroke-opacity="${sel?'0.95':'0.4'}"/>`;}).join('');const nodes=S.u.characters.map(c=>{const p=S.positions[c.id];if(!p)return '';const[col]=color(c);const sel=S.selected?.type==='character'&&S.selected.id===c.id;const size=sel?18:12,half=size/2;return `<rect data-map-node="${c.id}" x="${p.x-half}" y="${p.y-half}" width="${size}" height="${size}" fill="${col}" stroke="#ffffff" stroke-width="2" class="minimap-dot"/>`;}).join('');const lens=`<rect class="minimap-lens" x="${S.box.x}" y="${S.box.y}" width="${S.box.w}" height="${S.box.h}" rx="0"/>`;svg.innerHTML=edges+nodes+lens;bindMinimap(svg,minX,minY,mapW,mapH);}
function updateMinimapLens(){const svg=$('#minimap-svg');if(!svg)return;const lens=svg.querySelector('.minimap-lens');if(lens){lens.setAttribute('x',S.box.x);lens.setAttribute('y',S.box.y);lens.setAttribute('width',S.box.w);lens.setAttribute('height',S.box.h);}}
function updateMinimapNode(id,nx,ny){const svg=$('#minimap-svg');if(!svg||!S.minimapVisible)return;const dot=svg.querySelector(`[data-map-node="${id}"]`);if(dot){const size=Number(dot.getAttribute('width'))||12;dot.setAttribute('x',nx-size/2);dot.setAttribute('y',ny-size/2);}S.u.relationships.forEach(r=>{if(r.source===id||r.target===id){const line=svg.querySelector(`[data-map-edge="${r.id}"]`);if(line){const a=S.positions[r.source],b=S.positions[r.target];if(a&&b){line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);}}}});}
function bindMinimap(svg,minX,minY,mapW,mapH){if(svg.dataset.bound)return;svg.dataset.bound='1';let draggingLens=false,startPt=null,startBox=null;const getMapPt=ev=>{const rect=svg.getBoundingClientRect(),nx=(ev.clientX-rect.left)/rect.width,ny=(ev.clientY-rect.top)/rect.height;return {x:minX+nx*mapW,y:minY+ny*mapH};};svg.onpointerdown=ev=>{ev.stopPropagation();const lens=ev.target.closest('.minimap-lens'),pt=getMapPt(ev);draggingLens=true;startPt=pt;startBox={...S.box};svg.setPointerCapture(ev.pointerId);if(!lens){S.box.x=pt.x-S.box.w/2;S.box.y=pt.y-S.box.h/2;startBox={...S.box};const canvas=$('#graph-canvas');if(canvas)canvas.setAttribute('viewBox',`${S.box.x} ${S.box.y} ${S.box.w} ${S.box.h}`);updateMinimapLens();}};svg.onpointermove=ev=>{if(!draggingLens)return;ev.stopPropagation();const pt=getMapPt(ev);S.box.x=startBox.x+(pt.x-startPt.x);S.box.y=startBox.y+(pt.y-startPt.y);const canvas=$('#graph-canvas');if(canvas)canvas.setAttribute('viewBox',`${S.box.x} ${S.box.y} ${S.box.w} ${S.box.h}`);updateMinimapLens();};const stopDrag=ev=>{if(!draggingLens)return;draggingLens=false;try{svg.releasePointerCapture(ev.pointerId);}catch{}store();drawGraph();drawMinimap();};svg.onpointerup=stopDrag;svg.onpointercancel=stopDrag;}
function edgeGeometry(r,i){const a=S.positions[r.source],b=S.positions[r.target];if(!a||!b)return null;let dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1;const ra=1/Math.max(Math.abs(dx)/112,Math.abs(dy)/43,.001),rb=ra;const start={x:a.x+dx*ra,y:a.y+dy*ra},end={x:b.x-dx*rb,y:b.y-dy*rb};const bend=((i%2)?1:-1)*22;const mid={x:(a.x+b.x)/2-dy/len*bend,y:(a.y+b.y)/2+dx/len*bend};const path=`M${start.x},${start.y} Q${mid.x},${mid.y} ${end.x},${end.y}`;const label={x:(start.x+2*mid.x+end.x)/4,y:(start.y+2*mid.y+end.y)/4};const width=Math.min(170,Math.max(52,r.label.length*6+18));return {path,label,width};}
function updateEdges(svg,nodeId){S.u.relationships.forEach((r,i)=>{if(r.source!==nodeId&&r.target!==nodeId)return;const g=edgeGeometry(r,i);if(!g)return;const edgeEl=svg.querySelector(`[data-edge="${r.id}"]`);if(!edgeEl)return;const p1=edgeEl.querySelector('.edge-path');if(p1)p1.setAttribute('d',g.path);const p2=edgeEl.querySelector('.edge-hit');if(p2)p2.setAttribute('d',g.path);const bg=edgeEl.querySelector('.edge-label-bg');if(bg){bg.setAttribute('x',g.label.x-g.width/2);bg.setAttribute('y',g.label.y-11);}const txt=edgeEl.querySelector('.edge-label');if(txt){txt.setAttribute('x',g.label.x);txt.setAttribute('y',g.label.y+4);}});}
function graphInner(){defaultPositions();const sel=S.selected;let connectedNodes=null,connectedEdges=null;if(sel?.type==='character'){const rels=S.u.relationships.filter(r=>r.source===sel.id||r.target===sel.id);connectedEdges=new Set(rels.map(r=>r.id));connectedNodes=new Set([sel.id,...rels.flatMap(r=>[r.source,r.target])]);}else if(sel?.type==='edge'){const rel=S.u.relationships.find(r=>r.id===sel.id);if(rel){connectedEdges=new Set([rel.id]);connectedNodes=new Set([rel.source,rel.target]);}}const defs=`<defs><filter id="ink-bleed" x="-20%" y="-20%" width="140%" height="140%"><feTurbulence type="fractalNoise" baseFrequency="0.04" numOctaves="3" result="noise"/><feDisplacementMap in="SourceGraphic" in2="noise" scale="3.2" xChannelSelector="R" yChannelSelector="G"/></filter></defs>`;const edges=S.u.relationships.map((r,i)=>{const g=edgeGeometry(r,i);if(!g)return '';const tension=r.intensity>=5?'high-tension':'';const isSel=sel?.type==='edge'&&sel.id===r.id;const isHigh=connectedEdges&&connectedEdges.has(r.id)&&!isSel;const isDim=connectedEdges&&!connectedEdges.has(r.id);return `<g class="edge ${tension} ${isSel?'selected':''} ${isHigh?'highlighted':''} ${isDim?'dim':''}" data-edge="${r.id}" role="button" tabindex="0" aria-label="${e(C.names(S.u,r.source)+' '+r.label+' '+C.names(S.u,r.target))}"><path class="edge-path" d="${g.path}"/><path class="edge-hit" d="${g.path}"/><rect class="edge-label-bg" x="${g.label.x-g.width/2}" y="${g.label.y-11}" width="${g.width}" height="22" rx="0"/><text class="edge-label" text-anchor="middle" x="${g.label.x}" y="${g.label.y+4}">${e(r.label.length>25?r.label.slice(0,24)+'…':r.label)}</text></g>`;}).join('');const nodes=S.u.characters.map((c,i)=>{const p=S.positions[c.id],[col,wash]=color(c);const isSel=sel?.type==='character'&&sel.id===c.id;const isPeer=connectedNodes&&connectedNodes.has(c.id)&&!isSel;const isDim=connectedNodes&&!connectedNodes.has(c.id);return `<g class="graph-node ${isSel?'selected':''} ${isPeer?'connected-peer':''} ${isDim?'dim':''}" style="--stagger-i: ${i};" data-node="${c.id}" transform="translate(${p.x-112},${p.y-40})" role="button" tabindex="0" aria-label="Inspect ${e(c.name)}"><rect class="body" width="224" height="80" rx="0"/><rect x="12" y="18" width="34" height="44" rx="0" fill="${wash}"/><text class="n-initial" x="29" y="46" fill="${col}" text-anchor="middle">${e(initials(c.name))}</text><text class="n-name" x="56" y="34">${e(c.name.length>18?c.name.split(' ')[0]:c.name)}</text><text class="n-role" x="56" y="52">${e(c.role.split('·')[0].trim().slice(0,22))}</text><rect x="204" y="10" width="6" height="6" fill="${col}"/></g>`;}).join('');return defs+edges+nodes;}
function drawGraph(){const svg=$('#graph-canvas');if(!svg)return;const b=S.box;svg.setAttribute('viewBox',`${b.x} ${b.y} ${b.w} ${b.h}`);svg.innerHTML=graphInner();drawMinimap();}
function graphPoint(svg,evt){return new DOMPoint(evt.clientX,evt.clientY).matrixTransform(svg.getScreenCTM().inverse());}
let glideId=null;
function updateGraphSelection(svg,preview=null){if(!svg)return;const target=preview!==null?preview:S.selected;let connectedNodes=null,connectedEdges=null;if(target?.type==='character'){const cid=target.id;const rels=S.u.relationships.filter(r=>r.source===cid||r.target===cid);connectedEdges=new Set(rels.map(r=>r.id));connectedNodes=new Set([cid,...rels.flatMap(r=>[r.source,r.target])]);}else if(target?.type==='edge'){const rel=S.u.relationships.find(r=>r.id===target.id);if(rel){connectedEdges=new Set([rel.id]);connectedNodes=new Set([rel.source,rel.target]);}}svg.querySelectorAll('.graph-node').forEach(el=>{const id=el.dataset.node;const isPrimary=target?.type==='character'&&target.id===id;const isPeer=connectedNodes&&connectedNodes.has(id)&&!isPrimary;const isDim=connectedNodes&&!connectedNodes.has(id);el.classList.toggle('selected',S.selected?.type==='character'&&S.selected.id===id);el.classList.toggle('active-hover',!!preview&&isPrimary);el.classList.toggle('connected-peer',!!isPeer);el.classList.toggle('dim',!!isDim);});svg.querySelectorAll('.edge').forEach(el=>{const id=el.dataset.edge;const isSelectedEdge=S.selected?.type==='edge'&&S.selected.id===id;const isConnected=connectedEdges&&connectedEdges.has(id);const isDim=connectedEdges&&!connectedEdges.has(id);el.classList.toggle('selected',isSelectedEdge);el.classList.toggle('highlighted',!!isConnected&&!isSelectedEdge);el.classList.toggle('dim',!!isDim);});if(preview===null){document.querySelectorAll('.character-tile').forEach(el=>{el.classList.toggle('active',S.selected?.type==='character'&&el.dataset.id===S.selected.id);});}}
function bindGraph(){const svg=$('#graph-canvas');if(!svg)return;let drag=null,lastMoveTime=0,velX=0,velY=0,rafMove=null,pendingPt=null,currentHoverKey=null;
 const updateDrag=()=>{rafMove=null;if(!drag||!drag.moved||!pendingPt)return;const p=pendingPt,now=performance.now(),dt=Math.max(1,now-lastMoveTime);if(!drag.id){velX=(drag.pt.x-p.x)/dt;velY=(drag.pt.y-p.y)/dt;S.box.x+=drag.pt.x-p.x;S.box.y+=drag.pt.y-p.y;svg.setAttribute('viewBox',`${S.box.x} ${S.box.y} ${S.box.w} ${S.box.h}`);updateMinimapLens();}else{const nx=Math.max(-400,Math.min(1600,drag.start.x+p.x-drag.pt.x));const ny=Math.max(-300,Math.min(1100,drag.start.y+p.y-drag.pt.y));S.positions[drag.id]={x:nx,y:ny};const nodeEl=svg.querySelector(`[data-node="${drag.id}"]`);if(nodeEl)nodeEl.setAttribute('transform',`translate(${nx-87},${ny-40})`);updateEdges(svg,drag.id);updateMinimapNode(drag.id,nx,ny);}lastMoveTime=now;};
 svg.onpointerdown=ev=>{if(ev.button!==0)return;if(glideId){cancelAnimationFrame(glideId);glideId=null;}if(rafMove){cancelAnimationFrame(rafMove);rafMove=null;}const node=ev.target.closest('[data-node]'),edge=ev.target.closest('[data-edge]');const p=graphPoint(svg,ev);drag={id:node?.dataset.node||null,edgeId:(!node&&edge)?edge.dataset.edge:null,pt:p,client:{x:ev.clientX,y:ev.clientY},start:node?{...S.positions[node.dataset.node]}:{...S.box},moved:false};velX=0;velY=0;lastMoveTime=performance.now();svg.classList.add('dragging');if(drag.id){const nodeEl=svg.querySelector(`[data-node="${drag.id}"]`);if(nodeEl)nodeEl.classList.add('is-dragging');}svg.setPointerCapture(ev.pointerId);};
 svg.onpointermove=ev=>{if(!drag)return;if(!drag.moved&&Math.hypot(ev.clientX-drag.client.x,ev.clientY-drag.client.y)>3){drag.moved=true;}if(!drag.moved)return;pendingPt=graphPoint(svg,ev);if(!rafMove){rafMove=requestAnimationFrame(updateDrag);}};
 svg.onpointerup=ev=>{if(!drag)return;if(rafMove){cancelAnimationFrame(rafMove);rafMove=null;updateDrag();}const d=drag;drag=null;pendingPt=null;svg.classList.remove('dragging');try{svg.releasePointerCapture(ev.pointerId);}catch{}if(d.id){const nodeEl=svg.querySelector(`[data-node="${d.id}"]`);if(nodeEl)nodeEl.classList.remove('is-dragging');}if(d.moved){svg.dataset.dragged='1';setTimeout(()=>delete svg.dataset.dragged,120);store();if(!d.id&&Math.hypot(velX,velY)>0.05&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){let vx=velX*14,vy=velY*14;const glide=()=>{if(Math.hypot(vx,vy)<0.2){store();drawMinimap();return;}S.box.x+=vx;S.box.y+=vy;vx*=0.90;vy*=0.90;svg.setAttribute('viewBox',`${S.box.x} ${S.box.y} ${S.box.w} ${S.box.h}`);updateMinimapLens();glideId=requestAnimationFrame(glide);};glideId=requestAnimationFrame(glide);}else if(d.id){if(S.selected?.type!=='character'||S.selected.id!==d.id){S.selected={type:'character',id:d.id};const ins=$('.inspector');if(ins)ins.innerHTML=renderInspector();updateGraphSelection(svg);}drawMinimap();store();}}else{if(d.id){S.selected={type:'character',id:d.id};}else if(d.edgeId){S.selected={type:'edge',id:d.edgeId};}else{S.selected=null;}const ins=$('.inspector');if(ins)ins.innerHTML=renderInspector();updateGraphSelection(svg);store();}};
 svg.onpointercancel=()=>{if(rafMove){cancelAnimationFrame(rafMove);rafMove=null;}if(drag){if(drag.id){const nodeEl=svg.querySelector(`[data-node="${drag.id}"]`);if(nodeEl)nodeEl.classList.remove('is-dragging');}drag=null;pendingPt=null;svg.classList.remove('dragging');store();drawMinimap();}};
 svg.onpointerover=ev=>{if(svg.classList.contains('dragging')||drag)return;const node=ev.target.closest('[data-node]'),edge=ev.target.closest('[data-edge]');let key=null,preview=null;if(node){key='node:'+node.dataset.node;preview={type:'character',id:node.dataset.node};}else if(edge){key='edge:'+edge.dataset.edge;preview={type:'edge',id:edge.dataset.edge};}if(key!==currentHoverKey){currentHoverKey=key;updateGraphSelection(svg,preview);}};
 svg.onpointerleave=()=>{if(svg.classList.contains('dragging')||drag)return;if(currentHoverKey!==null){currentHoverKey=null;updateGraphSelection(svg,null);}};
 document.querySelectorAll('.character-tile').forEach(tile=>{tile.onpointerenter=()=>{const canvas=$('#graph-canvas');if(canvas&&!canvas.classList.contains('dragging'))updateGraphSelection(canvas,{type:'character',id:tile.dataset.id});};tile.onpointerleave=()=>{const canvas=$('#graph-canvas');if(canvas&&!canvas.classList.contains('dragging'))updateGraphSelection(canvas,null);};});
 svg.onclick=ev=>{ev.preventDefault();};
 svg.onkeydown=ev=>{const node=ev.target.closest('[data-node]'),edge=ev.target.closest('[data-edge]');if(['Enter',' '].includes(ev.key)){ev.preventDefault();S.selected={type:node?'character':'edge',id:node?.dataset.node||edge?.dataset.edge};const ins=$('.inspector');if(ins)ins.innerHTML=renderInspector();updateGraphSelection(svg);store();$('.inspector .panel-title')?.scrollIntoView({block:'nearest'});}else if(node&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key)){ev.preventDefault();const p=S.positions[node.dataset.node];p.x+=ev.key==='ArrowRight'?15:ev.key==='ArrowLeft'?-15:0;p.y+=ev.key==='ArrowDown'?15:ev.key==='ArrowUp'?-15:0;node.setAttribute('transform',`translate(${p.x-87},${p.y-40})`);updateEdges(svg,node.dataset.node);updateMinimapNode(node.dataset.node,p.x,p.y);store();}};
 svg.addEventListener('wheel',ev=>{ev.preventDefault();const f=ev.deltaY>0?1.1:.91,p=graphPoint(svg,ev);svg.classList.add('arranging');zoom(f,p);svg.classList.remove('arranging');},{passive:false});}
function zoom(f,p){const b=S.box,w=Math.max(350,Math.min(2200,b.w*f)),h=w*2/3,c=p||{x:b.x+b.w/2,y:b.y+b.h/2};const ratio=w/b.w;S.box={x:c.x-(c.x-b.x)*ratio,y:c.y-(c.y-b.y)*ratio,w,h};drawGraph();store();}
function renderAnalyst(){
 const a=C.castAnalysis(S.u),lp=a.linchpin,pk=a.powderKeg,out=a.outsider,m=a.metrics;
 return `<div class="section-head"><div><div class="eyebrow">Structural Cast Intelligence</div><h2>Automated Cast & Tension Analysis</h2><p>Deterministic graph topology metrics evaluating narrative load-bearing characters, volatility hot-spots, and structural outsiders.</p></div></div>
<div class="analyst-grid">
 <article class="analyst-card stagger-item" style="--stagger-i: 0;">
  <span class="analyst-badge badge-linchpin">Narrative Linchpin</span>
  <div class="analyst-stat">${lp.character?e(lp.character.name):'None'}<small>${Math.max(0,lp.connections)} connection${lp.connections===1?'':'s'}</small></div>
  <p class="muted">${e(lp.summary)}</p>
  ${lp.character?`<div class="card-actions" style="margin-top:16px">${btn('Inspect node','select-character','small',`data-id="${lp.character.id}"`)}</div>`:''}
 </article>
 <article class="analyst-card stagger-item" style="--stagger-i: 1;">
  <span class="analyst-badge badge-powderkeg">Powder Keg Point</span>
  <div class="analyst-stat">${pk.relationship?`${pk.intensity}/5 Pressure`:'None'}<small>${pk.relationship?e(pk.relationship.label):''}</small></div>
  <p class="muted">${e(pk.summary)}</p>
  ${pk.relationship?`<div class="card-actions" style="margin-top:16px">${btn('Inspect edge','select-edge','small',`data-id="${pk.relationship.id}"`)}</div>`:''}
 </article>
 <article class="analyst-card stagger-item" style="--stagger-i: 2;">
  <span class="analyst-badge badge-outsider">Structural Outsider</span>
  <div class="analyst-stat">${out.character?e(out.character.name):'None'}<small>${Math.max(0,out.connections)} connection${out.connections===1?'':'s'}</small></div>
  <p class="muted">${e(out.summary)}</p>
  ${out.character?`<div class="card-actions" style="margin-top:16px">${btn('Inspect node','select-character','small',`data-id="${out.character.id}"`)}</div>`:''}
 </article>
</div>
<div class="analyst-footer-metrics">
 <div class="metric-box"><span class="lbl">Approved Cast</span><span class="val">${m.castSize} Characters</span></div>
 <div class="metric-box"><span class="lbl">Total Connections</span><span class="val">${m.relationshipCount} Edges</span></div>
 <div class="metric-box"><span class="lbl">High Volatility (≥4)</span><span class="val">${m.highPressureCount} Nodes</span></div>
 <div class="metric-box"><span class="lbl">Average Cast Pressure</span><span class="val">${m.avgPressure} / 5.0</span></div>
</div>`;
}



function renderChronology(){
 const acts=C.storyChronology(S.u);
 return `<div class="section-head"><div><div class="eyebrow">Plot Mechanics & Turning Points</div><h2>Narrative Chronology Timeline</h2><p>Generative sequence mapping relationship breaking points and collision wants into classic dramatic act progression.</p></div></div>
<div class="chronology-timeline">
 ${acts.map((act,actIdx)=>`<section class="act-group stagger-item" style="--stagger-i: ${actIdx};">
  <header class="act-header">
   <div style="display:flex;align-items:center;gap:10px">
    <span style="display:inline-block;width:10px;height:10px;background:${act.color};border:1px solid var(--ink)"></span>
    <h3>${e(act.act)}</h3>
   </div>
   <span class="subtitle">${e(act.subtitle)}</span>
  </header>
  <div class="event-chain">
   ${act.events.map(ev=>`<article class="event-item">
    <span class="event-tag">${e(ev.tag)} · Intensity ${ev.intensity}/5</span>
    <h4 class="event-title">${e(ev.title)}</h4>
    <p class="event-summary">${e(ev.summary)}</p>
    ${ev.tension?`<p class="muted" style="font-size:var(--fs-cap);font-style:italic">Tension: ${e(ev.tension)}</p>`:''}
    <div class="event-involved">
     ${ev.characters.map(cid=>`<button class="tag" data-action="select-character" data-id="${cid}">${e(C.names(S.u,cid))}</button>`).join('')}
    </div>
   </article>`).join('')||'<p class="muted" style="font-size:var(--fs-sm)">No structural events mapped in this phase.</p>'}
  </div>
 </section>`).join('')}
</div>`;
}

function renderSeeds(){const seedsList=C.seeds(S.u);return `<div class="section-head"><div><div class="eyebrow">Relationships in motion</div><h2>Scenes that come from your cast.</h2><p>Compiled from the highest-pressure approved edges, not an unrelated plot generator.</p></div>${btn(icon('download')+'Export seeds','save-seeds','small')}</div><div class="content-grid">${seedsList.map((s,i)=>{const isCatalyst=i===0,hookChar=s.hook?s.hook.charAt(0):'',hookRest=s.hook?s.hook.slice(1):'';return `<article class="card stagger-item ${isCatalyst?'seed-card catalyst':''}" style="--stagger-i: ${i};"><div class="seed-number">${isCatalyst?'★ Catalyst Seed 01':`0${i+1}`}</div><h3>${e(s.title)}</h3><div class="card-tags">${s.characters.map(id=>`<button class="tag" data-action="select-character" data-id="${id}">${e(C.names(S.u,id))}</button>`).join('')}</div><p><strong>${e(s.trigger)}</strong></p><p class="mt">${isCatalyst?`<span class="drop-cap">${e(hookChar)}</span>`:''}${e(isCatalyst?hookRest:s.hook)}</p><div class="seed-question">${e(s.question)}</div><div class="card-actions">${btn('Inspect source relationship','select-edge','small',`data-id="${s.relationship_id}"`)}</div><div class="source-ref">Approved edge ${e(s.relationship_id)} · revision ${s.basis_revision}</div></article>`;}).join('')||'<div class="empty">Map relationships first.</div>'}</div>`;}
function renderAssets(){let list=C.assets(S.u).filter(x=>S.filter==='all'||x.category===S.filter);if(S.search)list=list.filter(x=>(x.title+' '+x.prompt).toLowerCase().includes(S.search.toLowerCase()));return `<div class="section-head"><div><div class="eyebrow">A shared visual language</div><h2>One universe. A coherent prompt kit.</h2><p>These are copy-ready prompts—not generated images. Every category uses the same approved visual direction.</p></div>${btn(icon('download')+'Export prompt kit','save-prompts','small')}</div><div class="palette">${S.u.visual.palette.map(x=>`<span class="palette-chip">${e(x)}</span>`).join('')}<span>${e(S.u.visual.style)}</span></div><div class="filterbar">${[['all','All prompts'],['portraits','Portraits'],['scenes','Scenes'],['presentation','Presentation'],['moodboard','Mood board']].map(([id,t])=>`<button class="filter ${S.filter===id?'active':''}" data-action="filter" data-value="${id}">${t}</button>`).join('')}<input class="searchbox" id="asset-search" aria-label="Search asset prompts" placeholder="Search prompts…" value="${e(S.search)}"></div><div class="content-grid">${list.map((a,i)=>`<article class="card prompt-card stagger-item" style="--stagger-i: ${i};"><div class="prompt-cover ${a.category}"><span class="symbol">${{portraits:'Aa',scenes:'⌑',presentation:'◫',moodboard:'⊞'}[a.category]}</span><span class="badge">${a.aspect_ratio} · prompt only</span></div><div class="prompt-body"><div class="eyebrow">${a.category}</div><h3>${e(a.title)}</h3><p class="prompt-excerpt">${e(a.prompt)}</p><div class="card-actions">${btn(icon('copy')+'Copy','copy-asset','primary small',`data-id="${a.id}"`)}${btn('Read prompt','view-asset','small',`data-id="${a.id}"`)}</div></div></article>`).join('')||'<p class="empty">No prompts match that search.</p>'}</div>`;}
function renderSuggestions(){const g=C.gaps(S.u);return `<div class="section-head"><div><div class="eyebrow">Possibilities, not prescriptions</div><h2>What would another person change?</h2><p>Suggestions stay outside the canon until you accept them. A story does not require every archetype.</p></div><span class="badge">${S.u.suggestions.filter(p=>p.status==='pending').length} awaiting your judgment</span></div>${g.length?`<div class="wide-banner"><div>${g.map(x=>`<strong>${e(x.title)}</strong><small>${e(x.detail)}</small>`).join('<br>')}</div></div>`:''}<div class="proposals">${S.u.suggestions.map((p,i)=>`<article class="card stagger-item" style="--stagger-i: ${i};"><div class="proposal-status">${p.status==='pending'?'Proposed addition · not canon':p.status==='accepted'?'✓ Accepted into the cast':'Not included'}</div><h3>${e(p.character.name)}</h3><div class="detail-sub">${e(p.character.role)} · ${e(p.character.archetype_label)}</div><div class="tension-box"><span class="detail-label">${e(p.gap)}</span><p>${e(p.rationale)}</p></div>${block('What this changes',p.impact)}<div class="quote">“${e(p.character.voice_samples[0])}”</div><div class="card-tags">${p.relationships.map(r=>`<span class="tag">${e(r.label)} · ${e(C.names(S.u,r.source===p.character.id?r.target:r.source))}</span>`).join('')}</div><div class="card-actions">${btn('Read full proposal','proposal','small',`data-id="${p.id}"`)}${p.status==='pending'?btn(icon('plus')+'Adopt into canon','accept','primary small',`data-id="${p.id}"`)+btn('Shelve proposal','reject','ghost small',`data-id="${p.id}"`):''}</div></article>`).join('')||'<div class="empty">Complete relationship mapping to receive optional additions.</div>'}</div><div class="activity">Accepting adds the character and proposed edges to the single approved record. Prompts and story seeds then compile from that updated record. Undo restores the previous decision.</div>`;}

let lastFocus=null;
function modal(title,body,footer='',wide=false,subtitle='',trigger=null){lastFocus=trigger||document.activeElement;let origStyle='';if(lastFocus&&lastFocus.getBoundingClientRect){const r=lastFocus.getBoundingClientRect(),ox=Math.round(r.left+r.width/2),oy=Math.round(r.top+r.height/2);origStyle=`--orig-x:${ox}px;--orig-y:${oy}px;`;}modalRoot.innerHTML=`<div class="modal-overlay"><section class="modal ${wide?'wide':''}" style="${origStyle}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-head"><div><h2 id="modal-title">${e(title)}</h2>${subtitle?`<p>${e(subtitle)}</p>`:''}</div><button class="iconbtn" data-action="close-modal" aria-label="Close dialog">${icon('close')}</button></header><div class="modal-body">${body}</div>${footer?`<footer class="modal-footer">${footer}</footer>`:''}</section></div>`;setTimeout(()=>modalRoot.querySelector('textarea,input,select,button')?.focus(),40);}
function closeModal(){const m=modalRoot.querySelector('.modal');if(m&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){m.classList.add('closing');setTimeout(()=>{modalRoot.innerHTML='';if(lastFocus&&lastFocus.focus){try{lastFocus.focus();}catch{}}},170);}else{modalRoot.innerHTML='';if(lastFocus&&lastFocus.focus){try{lastFocus.focus();}catch{}}}}
function formField(label,name,value='',rows=0,placeholder=''){const p=placeholder?` placeholder="${e(placeholder)}"`:'';return `<label class="form-field"><span>${e(label)}</span>${rows?`<textarea name="${name}" rows="${rows}"${p}>${e(value)}</textarea>`:`<input name="${name}" value="${e(value)}"${p}>`}</label>`;}
function showNew(){modal('Begin with a premise.',`<p class="muted">Describe the people, place or conflict you can already imagine. Leave room for discovery.</p><form id="new-form" style="margin-top:18px">${formField('Your story concept','concept','',4,'e.g., A disgraced archivist and a renegade cartographer race to decode an empire’s forgotten stars…')}<div class="form-row"><label class="form-field"><span>Non-game format</span><select name="format"><option>Television pilot</option><option>Novel outline</option><option>Short story</option><option>Classroom writing exercise</option><option>Fictional brand narrative</option></select></label><label class="form-field"><span>Initial cast</span><select name="count"><option>4</option><option selected>5</option><option>6</option></select></label></div><div class="form-row">${formField('Genre (optional)','genre','',0,'e.g., Historical Speculative Fiction')}${formField('Tone (optional)','tone','',0,'e.g., Intimate, atmospheric, quietly suspenseful')}</div><div id="new-error"></div></form><div class="eyebrow" style="margin-top:18px">Or explore a complete, clearly labeled example</div><div class="examples-row">${Object.entries(B.examples).map(([id,u])=>`<button class="example-btn" data-action="example" data-value="${e(id)}"><b>${e(u.title)}</b><small>${e(u.genre)} · curated, no live call</small></button>`).join('')}</div>`,btn('Import universe','import-universe','small')+btn('Cast characters <span class="icon-capsule">'+icon('arrow')+'</span>','create','primary'),false,'First useful draft is a target experience, not a latency guarantee.');}
function showAddStory(){modal('Add a universe',`<div class="callout"><strong>Three ways to fill this showcase:</strong></div><ul class="bullets"><li><strong>Drag &amp; drop.</strong> Drop a universe <code>.json</code> anywhere on this page.</li><li><strong>Add a universe.</strong> Open a file with the browser picker.</li><li><strong>WorkBuddy.</strong> Generate a full universe in chat, then download it (or it is handed back as a file) and drop it here.</li></ul><p class="muted">This page is fully offline. It never connects to a server, and it never sends your story anywhere. Editing, validation and exports all run in your browser.</p>`,btn('Open a file','import-universe','small')+btn('Close','close-modal','primary'));}
function showEditCharacter(id){const c=S.u.characters.find(c=>c.id===id);if(!c)return;modal('Edit '+c.name,`<form id="edit-character-form" data-id="${c.id}"><div class="form-row">${formField('Name','name',c.name)}${formField('Narrative role','role',c.role)}</div>${formField('Communication style','communication_style',c.communication_style,2,'Cadence, verbal deflection, conversational rhythm...')}<div class="form-row">${formField('Emotional baseline','emotional_baseline',c.emotional_baseline)}${formField('Appearance','appearance',c.appearance,2,'Visual silhouette, distinctive garments, expressive cues...')}</div><div class="form-row">${formField('Core desire','core_desire',c.core_desire,2,'What do they yearn for more than safety?')}${formField('Core fear','core_fear',c.core_fear,2,'What vulnerability do they desperately conceal?')}</div>${formField('Backstory','backstory',c.backstory,3,'Formative crises, debts, or defining past allegiances...')}${formField('Voice samples — one per line, 3–5','voice_samples',c.voice_samples.join('\n'),4)}${formField('Tendencies — one per line, 2–6','tendencies',c.tendencies.join('\n'),3)}<div id="edit-error"></div></form>`,btn('Discard','close-modal','small')+btn('Commit to canon','save-character','primary'),true,'Names are updated throughout existing text. Other edits trigger an editorial review reminder.');}
function showEditEdge(id){const r=S.u.relationships.find(r=>r.id===id);if(!r)return;const ph={source_wants:'What does the initiator demand from this dynamic?',target_wants:'What does the counterpart protect or demand in return?',shared_history:'The defining shared crisis, betrayal, or turning point...',source_read:'How the initiator perceives and rationalizes their past together...',target_read:'How the counterpart interprets that exact same event...',tension:'The unresolved contradiction destabilizing them right now...',breaking_point:'The specific line or revelation that permanently fractures this bond...',story_potential:'The dramatic scenes and collisions waiting to erupt...'};modal('Edit this connection',`<form id="edge-form" data-id="${r.id}"><div class="form-row">${formField('Relationship label','label',r.label)}<label class="form-field"><span>Writer-set pressure, 1–5</span><input type="number" name="intensity" min="1" max="5" value="${r.intensity}"></label></div>${['source_wants','target_wants','shared_history','source_read','target_read','tension','breaking_point','story_potential'].map(k=>formField(k.replaceAll('_',' '),k,r[k],2,ph[k]||'')).join('')}<div id="edit-error"></div></form>`,btn('Discard','close-modal','small')+btn('Save connection','save-edge','primary'),true,C.names(S.u,r.source)+' ↔ '+C.names(S.u,r.target));}
function showEditStory(){modal('The story brief',`<form id="story-form">${formField('Title','title',S.u.title)}${formField('Concept','concept',S.u.concept,3)}<div class="form-row">${formField('Format','format',S.u.format)}${formField('Genre','genre',S.u.genre)}</div>${formField('Setting','setting',S.u.setting,2)}${formField('Tone','tone',S.u.tone)}${formField('Thematic core','thematic_thesis',S.u.thematic_thesis,2)}${formField('Palette — comma-separated','palette',S.u.visual.palette.join(', '))}${['lighting','texture','composition','style'].map(k=>formField(k[0].toUpperCase()+k.slice(1),k,S.u.visual[k],2)).join('')}<div id="edit-error"></div></form>`,btn('Discard','close-modal','small')+btn('Commit brief','save-story','primary'),true,'Changing the brief does not silently rewrite approved characters. Review coherence afterward.');}
function showProposal(id){const p=S.u.suggestions.find(x=>x.id===id);if(!p)return;modal(p.character.name,`<div class="callout"><strong>${e(p.gap)}</strong><br>${e(p.rationale)}<br><br><strong>Expected effect:</strong> ${e(p.impact)}</div>${profile(p.character)}<h3 class="modal-sub">Proposed connections</h3>${p.relationships.map(r=>`<div class="card" style="margin:12px 0"><h3>${e(r.label)} · ${e(C.names(S.u,r.source===p.character.id?r.target:r.source))}</h3>${block('Tension',r.tension)}${block('Story potential',r.story_potential)}</div>`).join('')}`,p.status==='pending'?btn('Shelve proposal','reject','small',`data-id="${p.id}"`)+btn('Adopt into canon','accept','primary',`data-id="${p.id}"`):btn('Close','close-modal'),true,'This profile is not canonical until you choose to include it.');}
function showExport(){const ready=S.phase==='studio';modal('Take your universe with you.',`<p class="muted" style="margin-bottom:18px">${ready?'Exports reflect the approved record at revision '+S.u.revision+'.':'This is a draft-stage export. Approve the cast and relationships to unlock the complete creative kit.'} Pending and rejected characters are excluded from the bible and visual prompts.</p>${S.analysisStale?'<div class="wide-banner warn">Editorial review is still flagged. The project archive records this limitation.</div>':''}<div class="export-grid">${[['save-zip','Complete story package','.zip · portable studio, bible, prompts, seeds, graph and source JSON','download'],['save-html','Portable studio','.html · open independently, no network or installation','graph'],['save-json','Universe JSON','.json · canonical editable data, including proposal decisions','book'],['save-bible','Character bible','.md · approved characters and relationship histories','book'],['save-prompts','Visual prompt kit','.md · categorized copy-ready prompts; no images','asset'],['save-svg','Relationship graph','.svg · scalable, editable vector map','graph']].map(([a,title,sub,ic])=>`<button class="export-option" data-action="${a}" ${!ready&&['save-zip','save-prompts'].includes(a)?'disabled':''}><span class="export-icon">${icon(ic)}</span><div class="export-meta"><strong>${title}</strong><small>${sub}</small></div></button>`).join('')}</div>`,btn('Import a universe','import-universe','small')+btn('Close','close-modal','primary'),true);}
function download(name,text,mime='text/plain;charset=utf-8'){const blob=new Blob([text],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function graphSVG(){defaultPositions();const vals=Object.values(S.positions),minx=Math.min(...vals.map(p=>p.x))-130,miny=Math.min(...vals.map(p=>p.y))-90,maxx=Math.max(...vals.map(p=>p.x))+130,maxy=Math.max(...vals.map(p=>p.y))+90;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${minx} ${miny} ${maxx-minx} ${maxy-miny}" width="1200" role="img" aria-label="${e(S.u.title)} relationships"><title>${e(S.u.title)} — relationship graph</title><style>.edge-path{stroke:#8c8070;stroke-width:1.8;fill:none;stroke-linecap:round}.edge-hit{display:none}.edge-label-bg{fill:#ffffff;stroke:#d5c8b4;stroke-width:1}.edge-label{font:11px "Segoe UI",Inter,sans-serif;fill:#181614}.graph-node .body{fill:#ffffff;stroke:#d5c8b4;stroke-width:1.5}.n-name{font:bold 15px "Iowan Old Style",Palatino,Georgia,serif;fill:#181614}.n-role{font:10px "JetBrains Mono",Menlo,monospace;fill:#524d46}.n-initial{font:20px "Iowan Old Style",Palatino,Georgia,serif;fill:#b45309}</style><rect x="${minx}" y="${miny}" width="${maxx-minx}" height="${maxy-miny}" fill="#f6f3eb"/>${graphInner()}</svg>`;}
function portableHTML(){const doc=document.documentElement.cloneNode(true);doc.querySelector('#root').innerHTML='';doc.querySelector('#modal-root').innerHTML='';doc.querySelector('#toast').textContent='';doc.querySelector('#toast').className='';const data={...B,portable:true,initial:C.clone(S.u),initial_view:{phase:S.phase,positions:S.positions,box:S.box,analysisStale:S.analysisStale,tab:S.tab,selected:S.selected},examples:B.examples};doc.querySelector('#boot-data').textContent=JSON.stringify(data).replace(/</g,'\\u003c');return '<!doctype html>\n'+doc.outerHTML;}
function exportFile(action){const u=S.u,prefix=C.slug(u.title);if(action==='save-json')download(prefix+'.universe.json',JSON.stringify(u,null,2),'application/json');if(action==='save-bible')download(prefix+'.bible.md',C.bible(u));if(action==='save-prompts')download(prefix+'.visual-prompts.md',C.promptKit(u));if(action==='save-seeds')download(prefix+'.story-seeds.md',C.seeds(u).map(s=>'# '+s.title+'\n\n'+s.trigger+'\n\n'+s.hook+'\n\n'+s.question).join('\n\n'));if(action==='save-svg')download(prefix+'.relationships.svg',graphSVG(),'image/svg+xml');if(action==='save-html')download(prefix+'.studio.html',portableHTML(),'text/html');if(action==='save-zip'){const files={'START-HERE.md':`# ${u.title}\n\nOpen studio.html in a browser. No network is needed for inspection, editing or export. New generation happens in WorkBuddy. The result is a file you drop onto this page.\n\nOrigin mode: ${u.provenance.mode}. Revision: ${u.revision}. Editorial review pending: ${S.analysisStale}. No images generated.\n\nPending/rejected proposals remain in universe.json for audit but are not part of the bible, graph or prompts.\n`,'universe.json':JSON.stringify(u,null,2),'workspace.json':JSON.stringify({phase:S.phase,positions:S.positions,box:S.box,editorial_review_needed:S.analysisStale},null,2),'character-bible.md':C.bible(u),'visual-prompts.md':C.promptKit(u),'story-seeds.json':JSON.stringify(C.seeds(u),null,2),'relationships.svg':graphSVG(),'validation.json':JSON.stringify({...C.validate(u,B.schema,B.archetypes),editorial_review_needed:S.analysisStale},null,2),'studio.html':portableHTML()};download(prefix+'.zip',C.zip(files),'application/zip');}toast('Export created from revision '+u.revision+'.');}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copied to clipboard.');}catch{const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();let ok=false;try{ok=document.execCommand('copy');}catch{}t.remove();if(ok)toast('Copied to clipboard.');else modal('Copy this text',`<textarea rows="14" aria-label="Text to copy">${e(text)}</textarea>`,btn('Close','close-modal'));}}
function getFile(kind){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.setAttribute('data-test-import',kind);input.onchange=async()=>{const f=input.files[0];if(!f)return;await loadFile(f);};document.body.appendChild(input);input.style.display='none';input.click();setTimeout(()=>input.remove(),120000);}
function showImportError(err){modal('Import was not applied',`<div class="error">${e(err.message||String(err))}</div><p class="muted">The current story has not changed. Correct the JSON and try again.</p>`,btn('Close','close-modal'));}
async function loadFile(f){try{if(f.size>2_000_000)throw Error('File exceeds the 2 MB local safety limit.');const text=await f.text();const data=JSON.parse(text.replace(/^\uFEFF/,''));applyImport(data,'universe');}catch(err){showImportError(err);}}
function applyImport(data,kind){const u=data.universe||data,check=C.validate(u,B.schema,B.archetypes);if(!check.ok)throw Error('That file is not a valid universe ('+(check.errors[0]||'unknown error')+').');const v=C.clone(u);if(!v.provenance)v.provenance={};v.provenance.mode='imported';if(!v.provenance.source)v.provenance.source='Imported file';if(S.u)S.undo.push(C.clone(S.u));S.u=v;S.awaiting=false;S.request=null;S.phase=u.relationships.length?'studio':'cast';S.tab='graph';S.positions={};S.box={x:0,y:0,w:900,h:600};S.selected=u.relationships.length?{type:'edge',id:u.relationships[0]?.id}:{type:'character',id:u.characters[0]?.id};closeModal();store();render();toast('Universe loaded.');}
function requestPayload(stage,input){return {request_id:'characteros-'+(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)),stage,input,base_fingerprint:stage==='cast'?'new':C.fingerprint(S.u),universe:stage==='cast'?null:C.clone(S.u)};}
function fallbackTask(req){return `CharacterOS — ${req.stage} request\n\nOpen the extracted project in WorkBuddy and read workbuddy/WORKFLOW.md, schema/universe.schema.json and the appropriate expert/Skills. Use the attached request JSON. Perform only its ${req.stage} stage. Return a JSON object containing request_id, base_fingerprint and universe. Preserve exact request IDs.\n\nFor cast: revision 1; copy input.concept and input.format exactly; exactly ${req.input.count} characters, 3–5 voice samples each, relationships: [], suggestions: []. For relationships: preserve approved characters and premise metadata exactly; increment revision by one; produce a connected graph with at least three meaningful two-perspective edges and 2–3 pending full-character suggestions, not yet canonical.\n\nUse the included THRESHOLD-derived communication lenses by their IDs. Include the required visual direction. No image generation. Return only the schema-conforming result.\n\nRequest ID: ${req.request_id}\nBase fingerprint: ${req.base_fingerprint}\n\nDownload the request JSON from this dialog. This page is fully offline.`;}
async function startRequest(stage,input){const req=requestPayload(stage,input);S.request={request:req,instructions:fallbackTask(req),created:Date.now()};S.awaiting=true;closeModal();render();showPending();}
function showPending(){if(!S.request)return;const p=S.request;modal('Ready for WorkBuddy',`<div class="callout"><span class="spinner"></span> Generating your universe…<br><span class="micro">${e(p.request.stage)} stage · ${e(p.request.request_id)}</span></div><p class="muted" style="margin-bottom:12px">Copy this task into WorkBuddy, or open the project there directly. When it hands back a universe, <strong>drag the .json onto this page</strong>.</p><pre class="code">${e(p.instructions)}</pre><div id="result-error" class="error"></div>`,btn('Cancel request','cancel-pending','small')+btn('Copy task','copy-task','small')+btn('Download request','download-request','small'),true);}
function cancelPending(){S.awaiting=false;S.request=null;closeModal();render();toast('Request canceled. The view stays empty until you load a result.');}
function example(id){const u=B.examples[id];if(!u)throw Error('Example not found.');S.u=C.clone(u);S.awaiting=false;S.phase='cast';S.tab='graph';S.selected={type:'character',id:u.characters[0].id};S.positions={};S.box={x:0,y:0,w:900,h:600};S.undo=[];S.analysisStale=false;S.filter='all';S.search='';closeModal();store();render();toast('Loaded a curated example. No model was called.');}
function showAbout(){modal('A connected universe—not a pile of ideas.',`<div class="callout"><strong>CharacterOS · 1.0.0</strong><br>A creative, non-game storytelling workbench adapted from THRESHOLD’s communication-style, directional-seed and relationship-state approach.</div><p class="muted">The dashboard has no external runtime dependencies. Its SVG graph, data validation, persistence and exports operate offline. Examples are never silently substituted.</p>${block('Verified source versus new contribution','Sixteen source NPC profiles in content/npc_templates.yaml were inspected at a pinned THRESHOLD commit. The displayed lens names and descriptive summaries are new narrative adaptations. Shared-history interpretations, editorial review and story-kit compilation are new workbench features. The original game runtime is not bundled.')}${block('WorkBuddy integration','Five instruction Skills and two expert role definitions are included. The team generates a universe in chat and hands the finished JSON back to this page (drag-and-drop). Host generation must be verified on the team’s installed WorkBuddy account. No native marketplace acceptance is claimed.')}${block('What the outputs mean','Story seeds and visual prompts are deterministically composed from the approved character and relationship text. They update after edits without an additional model call. No generated images, diagnostic scores, guaranteed latency or literary-quality certification.')}${block('Privacy','Browser-local storage holds this story on this device. Export copies intentionally include your story. This page never sends your story to any server.')}`,btn('Close','close-modal','primary'));}
async function action(name,target){const id=target?.dataset.id,val=target?.dataset.value;
 if(name==='new')return showNew();if(name==='close-modal')return closeModal();if(name==='connect')return showAddStory();if(name==='about')return showAbout();if(name==='export')return showExport();if(name==='pending')return showPending();if(name==='cancel-pending')return cancelPending();
 if(name==='toggle-cast'){transitionUI(()=>{S.castCollapsed=!S.castCollapsed;store();render();});return;}
 if(name==='toggle-minimap'){S.minimapVisible=!S.minimapVisible;store();const hud=$('#minimap-hud');if(hud){hud.classList.toggle('minimized',!S.minimapVisible);const sp=hud.querySelector('.minimap-head span.micro');if(sp)sp.textContent=S.minimapVisible?'▼':'▲';}drawMinimap();return;}
 if(name==='tab'){transitionUI(()=>{S.tab=val;S.search='';store();render();});return;}
 if(name==='filter'){S.filter=val;render();return;}
  if(name==='select-character'||name==='select-edge'){S.selected={type:name==='select-character'?'character':'edge',id};if(S.tab==='graph'&&S.phase!=='cast'){const ins=$('.inspector');if(ins)ins.innerHTML=renderInspector();updateGraphSelection($('#graph-canvas'));store();}else{transitionUI(()=>{S.tab='graph';render();store();});}return;}
 if(name==='profile'){const c=S.u.characters.find(c=>c.id===id);if(c)modal(c.name,profile(c),btn('Edit character','edit-character','small',`data-id="${c.id}"`)+btn('Close','close-modal','primary'));return;}
 if(name==='edit-character')return showEditCharacter(id);if(name==='edit-edge')return showEditEdge(id);if(name==='edit-story')return showEditStory();if(name==='proposal')return showProposal(id);
 if(name==='save-character'){const f=$('#edit-character-form'),values=Object.fromEntries(new FormData(f)),cid=f.dataset.id;try{let u=C.rename(S.u,cid,values.name),c=u.characters.find(x=>x.id===cid);for(const k of ['role','communication_style','emotional_baseline','appearance','core_desire','core_fear','backstory'])c[k]=values[k].trim();c.voice_samples=values.voice_samples.split('\n').map(x=>x.trim()).filter(Boolean);c.tendencies=values.tendencies.split('\n').map(x=>x.trim()).filter(Boolean);change(u,'Character updated. Review related story text.',true);closeModal();}catch(err){$('#edit-error').innerHTML=`<div class="error">${e(err.message)}</div>`;}return;}
 if(name==='save-edge'){const f=$('#edge-form'),v=Object.fromEntries(new FormData(f)),u=C.clone(S.u),r=u.relationships.find(r=>r.id===f.dataset.id);try{for(const [k,x]of Object.entries(v))r[k]=k==='intensity'?Number(x):x.trim();u.revision++;change(u,'Relationship updated; creative outputs now use its new text.',true);closeModal();}catch(err){$('#edit-error').innerHTML=`<div class="error">${e(err.message)}</div>`;}return;}
 if(name==='save-story'){const v=Object.fromEntries(new FormData($('#story-form'))),u=C.clone(S.u);try{for(const k of ['title','concept','format','genre','tone','setting','thematic_thesis'])u[k]=v[k].trim();u.visual.palette=v.palette.split(',').map(x=>x.trim()).filter(Boolean);for(const k of ['lighting','texture','composition','style'])u.visual[k]=v[k].trim();u.revision++;change(u,'Story brief updated. Review cast and relationships.',true);closeModal();}catch(err){$('#edit-error').innerHTML=`<div class="error">${e(err.message)}</div>`;}return;}
 if(name==='accept'||name==='reject'){const p=S.u.suggestions.find(p=>p.id===id);change(name==='accept'?C.accept(S.u,id):C.reject(S.u,id),name==='accept'?p.character.name+' added. Graph, seeds and prompts use the updated canon.':'Proposal excluded. It will not appear in your story outputs.');if(name==='accept'){S.selected={type:'character',id:p.character.id};}closeModal();store();render();return;}
 if(name==='undo'){if(S.undo.length){const old=S.undo.pop();S.u=old.u;S.phase=old.phase;S.analysisStale=old.analysisStale;if(!selected())S.selected={type:'character',id:S.u.characters[0].id};store();render();toast('Restored the previous approved record.');}return;}
 if(name==='reviewed'){S.analysisStale=false;store();render();toast('Editorial review acknowledged.');return;}
 if(name==='guided'){S.phase='cast';S.tab='graph';store();render();return;}
 if(name==='approve-cast'){if(S.u.relationships.length){S.phase='relationships';S.tab='graph';S.selected={type:'edge',id:S.u.relationships[0].id};store();render();return;}return startRequest('relationships',{concept:S.u.concept,format:S.u.format,genre:S.u.genre,tone:S.u.tone,count:Math.min(6,S.u.characters.length)});}
 if(name==='approve-map'){S.phase='studio';S.tab='assets';store();render();toast('Creative kit compiled from the approved cast and relationships.');return;}
 if(name==='edge-seed'){S.phase='studio';S.tab='seeds';render();store();return;}
 if(name==='zoom-in')return zoom(.82);if(name==='zoom-out')return zoom(1.22);if(name==='fit'){const p=Object.values(S.positions),minx=Math.min(...p.map(x=>x.x))-115,miny=Math.min(...p.map(x=>x.y))-80;let w=Math.max(...p.map(x=>x.x))+115-minx,h=Math.max(...p.map(x=>x.y))+80-miny;w=Math.max(w,h*1.5,500);h=w/1.5;S.box={x:minx,y:miny,w,h};drawGraph();store();return;}
 if(name==='layout'){S.positions={};S.box={x:0,y:0,w:900,h:600};drawGraph();store();return;}
 if(name==='view-asset'){const a=C.assets(S.u).find(a=>a.id===id);return modal(a.title,`<div class="palette"><span class="badge">${a.category}</span><span class="badge">Suggested ratio ${a.aspect_ratio}</span><span class="badge">Prompt only · revision ${a.revision}</span></div><pre class="code" style="margin-top:18px">${e(a.prompt)}</pre>`,btn(icon('copy')+'Copy prompt','copy-asset','primary',`data-id="${a.id}"`));}
 if(name==='copy-asset'){const a=C.assets(S.u).find(a=>a.id===id);return copy(a.prompt+'\n\nSuggested aspect ratio: '+a.aspect_ratio);}
 if(name.startsWith('save-'))return exportFile(name);
 if(name==='example')return example(val);
 if(name==='import-universe')return getFile('universe');
 if(name==='copy-task')return copy(S.request.instructions);
 if(name==='download-request'){const req=S.request.request;return download('characteros-request-'+req.request_id+'.json',JSON.stringify({...req,schema:B.schema,communication_lenses:B.archetypes,theme_resources:B.themes,instructions:S.request.instructions},null,2),'application/json');}
 if(name==='create'){const f=$('#new-form'),input=Object.fromEntries(new FormData(f));input.count=Number(input.count);if(input.concept.trim().length<15){$('#new-error').innerHTML='<div class="error">Give the story at least one complete sentence (15 characters or more).</div>';return;}await startRequest('cast',input);return;}
}
document.addEventListener('click',ev=>{const t=ev.target.closest('[data-action]');if(t&&!t.disabled){ev.preventDefault();Promise.resolve(action(t.dataset.action,t)).catch(err=>{toast(err.message);if(modalRoot.innerHTML&&$('#new-error'))$('#new-error').innerHTML=`<div class="error">${e(err.message)}</div>`;});}});
document.addEventListener('input',ev=>{if(ev.target.id==='asset-search'){const p=ev.target.selectionStart;S.search=ev.target.value;render();const n=$('#asset-search');n.focus();n.setSelectionRange(p,p);}});
document.addEventListener('keydown',ev=>{if(!modalRoot.innerHTML)return;if(ev.key==='Escape'){ev.preventDefault();closeModal();return;}if(ev.key==='Tab'){const focus=$$('button:not(:disabled),a[href],input,textarea,select,[tabindex="0"]',modalRoot).filter(x=>x.offsetParent!==null);const first=focus[0],last=focus.at(-1);if(ev.shiftKey&&document.activeElement===first){ev.preventDefault();last?.focus();}else if(!ev.shiftKey&&document.activeElement===last){ev.preventDefault();first?.focus();}}});
// Drag and drop: a universe .json dropped anywhere on the page loads it (option A/C).
window.addEventListener('dragover',ev=>{if(ev.dataTransfer&&ev.dataTransfer.types&&ev.dataTransfer.types.includes('Files')){ev.preventDefault();document.body.classList.add('dragging');}});
window.addEventListener('dragleave',ev=>{if(ev.relatedTarget==null)document.body.classList.remove('dragging');});
window.addEventListener('drop',async ev=>{const f=ev.dataTransfer&&ev.dataTransfer.files&&ev.dataTransfer.files[0];if(!f)return;ev.preventDefault();document.body.classList.remove('dragging');await loadFile(f);});
window.addEventListener('beforeunload',store);
render();
// Read-only diagnostics for acceptance tests; no privileged commands or credentials exposed.
window.CharacterOSInspect=()=>({universe:C.clone(S.u),phase:S.phase,positions:C.clone(S.positions),box:{...S.box},tab:S.tab,awaiting:S.awaiting,request_id:S.request?.request.request_id||null,editorial_review_needed:S.analysisStale});
window.SUAInspect=window.CharacterOSInspect;
})();
